### ISSUE TITLE
Czy da się wykorzystać funkcjonariusza do kopii zapasowej zaszyfrowanych dysków?

### ISSUE THREAD

**Issue by AKmatiAK** [funkcjonariusz/funkcjonariusz#1]
Patrząc na działanie programu zastanawia mnie czy jest mozliwość zgrania zaszyfrowanych partycji nie odszyfrowując ich i trzymając tylko jako kopię zapasową?

**Comment by tomaszklim** [comment]
Oczywiście da się to zrobić i nie potrzeba do tego Funkcjonariusza. Można po prostu wykonać kopię blokową całej partycji albo i dysku - przy niemal każdej metodzie szyfrowania, wszelkie informacje związane z szyfrowaniem znajdują się na samej partycji, więc można ją skopiować na inne urządzenie, a potem po prostu podawać przy podłączaniu inny identyfikator urządzenia - dajmy na to zamiast /dev/sdb1, np. /dev/sdm1.

Samo kopiowanie blokowe można z poziomu Linuxa wykonać programem "dd":

`dd if=/dev/sdb of=/dev/sdm status=progress`

Takie polecenie skopiuje blokowo cały dysk `sdb`, zapisując go na `sdm`, który musi mieć przynajmniej taką samą pojemność. Kopiowanie blokowe całego dysku spowoduje, że na nowym dysku automatycznie utworzy się ten sam układ partycji, więc nic więcej nie trzeba robić.

Tylko przed uruchomieniem takiego polecenia warto 3 razy sprawdzić, jakie identyfikatory urządzeń dostały nasze poszczególne dyski - bo to się potrafi zmienić po każdym restarcie komputera. Sprawdzić to można, wpisując na konsoli takie polecenie:

`ls -l /dev/disk/by-id/`

po czym weryfikując to co się pokazało z modelami i numerami seryjnymi dysków.

A jeśli mamy na komputerze tylko Windows?
- ściągamy sobie obraz Kali Linuxa Live: https://www.kali.org/get-kali/#kali-live
- nagrywamy go na pen drive'a: https://www.kali.org/docs/usb/live-usb-install-with-windows/
- uruchamiamy z niego komputer (w niebieskim menu wybieramy domyślną opcję)

**Comment by AKmatiAK** [comment]
o używaniu dd do kopii wiem, bardziej chodzi mi o rozwiązanie prostsze, gdzie odpalam pendriva klikam której partycji zrobić backup i gotowe - zastanawiałem się czy ten program nadaby się do takiej szybkiej kopii

**Comment by tomaszklim** [comment]
Raczej bym nie traktował Funkcjonariusza jako narzędzia do backupu własnych danych. Jasne, można, ale istnieją dużo lepsze narzędzia do backupu jako takiego.
